### ISSUE TITLE
🟢 [TRACKER] Publishing Kotlin SDK

### ISSUE THREAD

**Issue by jordan-pieces** [pieces-app/opensource#18]
This issue outlines all of the information around the progress and status of the Kotlin SDK.

#### 99% of the way there ! 
[🟩🟩🟩🟩🟩🟩🟩🟩🟩🟩🟩🟩🟩|-] 

#### Current Update 
Just waiting on some final testing to take place and concluding some research around maven publish, then we will be good to go on publish and to start building out micro projects around this SDK such as: 

- File Previews in the Sidebar while hovering any file
- Drag and drop a file 
- Code Transformation tool
- more...

#### Issues + Resources 
- [x] Issue 1 - https://github.com/pieces-app/pieces-os-client-sdk-for-kotlin/issues/1
- [x] Issue 2 - https://github.com/pieces-app/pieces-os-client-sdk-for-kotlin/issues/2
- [x] Issue 3 - https://github.com/pieces-app/pieces-os-client-sdk-for-kotlin/issues/4
- [x] Testing - https://github.com/pieces-app/pieces-os-client-sdk-for-kotlin/issues/3

**Comment by jordan-pieces** [comment]
Closing this issue - published on maven and can go through the issues on #23 to get info on issues 👍
